/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package De5;

import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author arohigh
 */
public class Form5 extends javax.swing.JFrame {

    /**
     * Creates new form Form5
     */
    public Form5() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfMasv = new javax.swing.JTextField();
        tfHoten = new javax.swing.JTextField();
        tfNgaysinh = new javax.swing.JTextField();
        tfDTB = new javax.swing.JTextField();
        tfHocphi = new javax.swing.JTextField();
        tfDonvi = new javax.swing.JTextField();
        tfLuong = new javax.swing.JTextField();
        nam = new javax.swing.JRadioButton();
        nu = new javax.swing.JRadioButton();
        svat = new javax.swing.JRadioButton();
        svmm = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Form nhap thong tin");

        jLabel2.setText("Ma SV");

        jLabel3.setText("Ho ten");

        jLabel4.setText("Ngay sinh");

        jLabel5.setText("Gioi tinh");

        jLabel6.setText("Diem TB");

        jLabel7.setText("Loai SV");

        jLabel8.setText("Hoc phi");

        jLabel9.setText("Don vi");

        jLabel10.setText("Luong");

        tfNgaysinh.setToolTipText("");

        tfHocphi.setToolTipText("");

        buttonGroup1.add(nam);
        nam.setText("Nam");
        nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namActionPerformed(evt);
            }
        });

        buttonGroup1.add(nu);
        nu.setText("Nu");

        buttonGroup2.add(svat);
        svat.setText("SVATTT");
        svat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svatActionPerformed(evt);
            }
        });

        buttonGroup2.add(svmm);
        svmm.setText("SVMM");
        svmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svmmActionPerformed(evt);
            }
        });

        jButton1.setText("Them SV");

        jButton2.setText("Luu SV");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfHocphi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMasv, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(svat)
                                .addGap(27, 27, 27)
                                .addComponent(svmm)))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(88, 88, 88))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfDTB, tfDonvi, tfHocphi, tfHoten, tfLuong, tfMasv, tfNgaysinh});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(svat)
                    .addComponent(svmm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfMasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nam)
                    .addComponent(nu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfDTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfHocphi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfDonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namActionPerformed

    private void svatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svatActionPerformed
        // TODO add your handling code here:
        //day la nut SVAT
//        tfHocphi.setEnabled(true);
//        tfDonvi.setEnabled(false);
//        tfLuong.setEnabled(false);
//        tfDonvi.setText("");
//        tfLuong.setText("");
        tfDonvi.setEnabled(false);
        tfDonvi.setText("");
        tfLuong.setEnabled(false);
        tfLuong.setText("");
        tfHocphi.setEnabled(true);
    }//GEN-LAST:event_svatActionPerformed

    private void svmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svmmActionPerformed
        // TODO add your handling code here:
//        tfHocphi.setEnabled(false);
//        tfHocphi.setText("");
//        tfDonvi.setEnabled(true);
//        tfLuong.setEnabled(true);
        tfHocphi.setEnabled(false);
        tfHocphi.setText("");
        tfDonvi.setEnabled(true);
        tfLuong.setEnabled(true);
    }//GEN-LAST:event_svmmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (!svat.isSelected() && !svmm.isSelected()) {
            JOptionPane.showMessageDialog(null, "ban phai chon Loai SV truoc!");
            return;
        }
        if (svat.isSelected()) {
            if (KiemTraRongSVAT() == true) {
                JOptionPane.showMessageDialog(null, "chua du thong tin cua SV ATTT");
                return;
            } else {
                try {
                    Float.parseFloat(tfDTB.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "ban nhap sai DTB");
                    return;
                }
                Float dtb = Float.parseFloat(tfDTB.getText());
                if (dtb > 10 || dtb < 0) {
                    JOptionPane.showMessageDialog(null, "ban phai nhap DTB trong khoang tu 0 -> 10");
                    return;
                }
                try {
                    Float.parseFloat(tfHocphi.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "ban nhap sai Hoc phi");
                    return;
                }

                SinhVienATTT sv = new SinhVienATTT(tfMasv.getText(), tfHoten.getText(), tfNgaysinh.getText(),
                        nam.isSelected() ? "nam" : "nu", dtb, Float.parseFloat(tfHocphi.getText()));
                try {
                    FileWriter fw = new FileWriter("svat.dat", true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.append(sv.MaSV + "$" + sv.HoTen + "$" + sv.NgaySinh + "$" + sv.GioiTinh + "$"
                            + sv.DTB + "$" + sv.getHocPhi().toString());
                    bw.newLine();
                    bw.close();
                    fw.close();
                    JOptionPane.showMessageDialog(null, "luu thanh cong");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "luu that bai");
                }
            }
        } else if (svmm.isSelected()) {
            if (KiemTraRongSVMM() == true) {
                JOptionPane.showMessageDialog(null, "chua du thong tin cua SV MM");
                return;
            } else {
                try {
                    Float.parseFloat(tfDTB.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "ban nhap sai DTB");
                    return;
                }
                Float dtb = Float.parseFloat(tfDTB.getText());
                if (dtb > 10 || dtb < 0) {
                    JOptionPane.showMessageDialog(null, "ban phai nhap DTB trong khoang tu 0 -> 10");
                    return;
                }
                try {
                    Float.parseFloat(tfLuong.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "ban nhap sai Luong");
                    return;
                }

                SinhVienMatMa sv = new SinhVienMatMa(tfMasv.getText(), tfHoten.getText(),
                        tfNgaysinh.getText(), nam.isSelected() ? "nam" : "nu", dtb, tfDonvi.getText(),
                        Float.parseFloat(tfLuong.getText()));
                try {
                    FileWriter fw = new FileWriter("svmm.dat", true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.append(sv.MaSV + "$" + sv.HoTen + "$" + sv.NgaySinh + "$" + sv.GioiTinh + "$"
                            + sv.DTB + "$" + sv.getDonVi() + "$" + sv.getLuong().toString());
                    bw.newLine();
                    bw.close();
                    fw.close();
                    JOptionPane.showMessageDialog(null, "luu thanh cong");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "luu that bai");
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form5().setVisible(true);
            }
        });
    }

    public boolean KiemTraRongSVAT() {
        if (tfMasv.getText().equals("") || tfHoten.getText().equals("")
                || tfNgaysinh.getText().equals("") || tfDTB.getText().equals("")
                || tfHocphi.getText().equals("") || (!nam.isSelected() && !nu.isSelected())) {
//            JOptionPane.showMessageDialog(null, "Ban chua dien du thong tin cho SV ATTT");
            return true;
        }
        return false;
    }

    public boolean KiemTraRongSVMM() {
        if (tfMasv.getText().equals("") || tfHoten.getText().equals("")
                || tfNgaysinh.getText().equals("") || tfDTB.getText().equals("")
                || tfDonvi.getText().equals("") || tfLuong.getText().equals("")
                || (!nam.isSelected() && !nu.isSelected())) {
//            JOptionPane.showMessageDialog(null, "Ban chua dien du thong tin cho SV Mat Ma");
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton nam;
    private javax.swing.JRadioButton nu;
    private javax.swing.JRadioButton svat;
    private javax.swing.JRadioButton svmm;
    private javax.swing.JTextField tfDTB;
    private javax.swing.JTextField tfDonvi;
    private javax.swing.JTextField tfHocphi;
    private javax.swing.JTextField tfHoten;
    private javax.swing.JTextField tfLuong;
    private javax.swing.JTextField tfMasv;
    private javax.swing.JTextField tfNgaysinh;
    // End of variables declaration//GEN-END:variables

}
